### ISSUE TITLE
Measured binaural decoders in all supported SRs

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-kernels#1]
Currently, the measured binaural decoders are available only at SR = 44.1kHz. This reflects the SR of the original HRTF measurements. ([CIPIC](http://interface.cipic.ucdavis.edu/sound/hrtf.html), [Listen](http://recherche.ircam.fr/equipes/salles/listen/))

Ideally, binaural decoders should be made available in all supported SRs.

NOTE: The Spherical Head model HRTFs are available in all supported SRs.

**Comment by ghost** [comment]
Last year, for http://ambisonic.xyz/, I up-sampled the ATK kernels (CIPIC and LISTEN) to 48KHz; it was required for browser running on systems with a default sample rate at 48Khz.  I used SRC from http://www.mega-nerd.com/SRC/. I don't if I did the conversion correctly, but it seems to work! :)

**Comment by joslloand** [comment]
Hi @marclava, this enhancement will be to generate kernels to the ATK's critical standard. Just resampling the current binaural decoders misses out these features:
- table centered linear phase
- signal decode up to Nyquist
- diffuse field EQ up to Nyquist

When we get the new kernels generated, you'll want to use these....

**Comment by joslloand** [comment]
Measured binaural decoder kernels interpolated & resampled (interpolated, decimated). SRs now supported:
- interpolated: 44100, 88200, 176400
- resampled: 48000, 96000, 192000

**Comment by joslloand** [comment]
@marclava, we'll soon be creating a new release with the updated kernels. In the meantime, feel free to download the new kernels. These are full bandwidth decoders and conform to the ATK's design criteria.

**Comment by lossius** [comment]
Thank you so much for doing this, @joslloand ! In a weeks time I'll start integrating this into the next version of atk-reaper, and I know many will appreciate this enhancement.

**Comment by joslloand** [comment]
@marclava, @hectorC, @henk-spook

[Version 1.2.1](https://github.com/ambisonictoolkit/atk-kernels/releases/tag/v1.2.1) fixes a number of issues found with the previous deployments. You'll be most interested in the support of SRs listed in this issue thread.

**Comment by HHHHHHHHHHHX** [comment]
Hi

That is really great. Will it now also be possible to use the YouTube /
Jump Inspector "hrtf", or would that only work in an ACN/SN3D format plugin?

https://storage.googleapis.com/jump-inspector/workflow/thrive.zip

Because I believe a lot of people are now making content for YouTube and
would love to hear how the spatial decoding will affect their mixes
beforehand.

Great work! Keep it up :)

Henk

Kattenburgerstraat 5
Building 024
1018 JA Amsterdam

_T_: +31615555694
_M_: henk@spook.fm

Spook.fm | Facebook http://www.facebook.com/spookamsterdam

2016-06-17 1:51 GMT+02:00 Joseph Anderson notifications@github.com:

**Comment by joslloand** [comment]
@henk-spook, we'll have to take a look at the YouTube / Jump Inspector. Thanks for the question. I'll open a new issue for that.

My gut feeling is "probably not". I've seen a little bit of traffic but haven't followed closely. I do remember seeing something that looked like using 8 virtual speakers at the vertices of a cube. While it will "work" this approach isn't ideal.

I suppose I could get in touch with them about changes that would allow the spherical harmonic strategy we're using.

New issue [opened here](https://github.com/ambisonictoolkit/atk-kernels/issues/11).

**Comment by joslloand** [comment]
See also: https://github.com/google/spatial-media/issues/114

@henk-spook , you may want to add a comment to the issue opened by @tumbleandyaw

**Comment by HHHHHHHHHHHX** [comment]
Thanks for pointing me to this thread. Couldn't agree more! :)

Kattenburgerstraat 5
Building 024
1018 JA Amsterdam

_T_: +31615555694
_M_: henk@spook.fm

Spook.fm | Facebook http://www.facebook.com/spookamsterdam

2016-07-20 19:32 GMT+02:00 Joseph Anderson notifications@github.com:
