### ISSUE TITLE
Add kernel support for 176.4 Hz

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-kernels#3]
This is one of the sample rates offered by most hi end audio cards as well as Reaper, and although it is probably less used than 196 kHz, one might imagine someone using it for oversampled processing targeting CD production (the sample rate is 4 x 44.1 kHz).

This issue relates to #1 .

**Comment by joslloand** [comment]
Added...

For atk-reaper a new installer will need to be made. For atk-sc3, users will need to download kernels.

**Comment by lossius** [comment]
Thanks! I've just made a v1.1.0 release of atk-kernels so that the newest version is available from the website.
