### ISSUE TITLE
FOA spherical decoder kernels are silent at 176.4 and 192kHz

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-kernels#6]
Marco Del Piano reports that the spherical 192000 files don’t work, the files are silent. Investigating, it seems like the new 176.4 kHz kernels for the spherical decoder has the same problem too.

The new kernels for encoders at 176.4 kHz looks good, this only seems to be an issue with the binaural decoders.

**Comment by joslloand** [comment]
@lossius, yes, I can confirm this.

Thanks to Marco Del Piano for noting this!

**Comment by joslloand** [comment]
Fixed by commit [40d16132a331e7bc7b30513f4c684c75a24e12ce](https://github.com/ambisonictoolkit/atk-kernels/commit/40d16132a331e7bc7b30513f4c684c75a24e12ce)

> **New spherical kernels for high SRs**
> Fixes “zeroed” kernels for SR = 176400, 192000. Additionally, the
> kernel size oversampling for kernel generation is now proportional for
> all SRs. Doing so also updates SR = 88200, 96000.

NOTE: The updates to kernels for SR = 88200, 96000 _should not_ not be audible. It is more of a "pretty" DSP thing.

**Comment by joslloand** [comment]
Also... we'll need to make a new release of the kernels. I'll be having a look at how this can be managed in relateion to #5.

First, though, I'm wanting to address #1, which is a weightier issue!
